extends: spectral:oas
rules:
  info-contact: off
  oas3-unused-component: off
  oas2-unused-definition: off
  properties-type-object:
    description: "type: object must have a properties sibling."
    given: "$..[?(@ && @.type == 'object')]"
    severity: error
    # must not be resolved because $ref-defined objects shall have its type
    # defined in the referenced schema, not the referencing field (and $ref 
    # must be the only property, anyway)
    resolved: false
    # type field must be defined and contain the value object
    then:
      - field: "properties"
        function: "truthy"
  items-type-array:
    description: "type: array must have an items sibling."
    given: "$..[?(@ && @.type == 'array')]"
    severity: error
    # must not be resolved because $ref-defined objects shall have its type
    # defined in the referenced schema, not the referencing field (and $ref 
    # must be the only property, anyway)
    resolved: false
    # type field must be defined and contain the value object
    then:
      - field: "items"
        function: "truthy"
except:
  'reference/tax_provider.yml':
    - oas3-schema
  'reference/carts.v3.yml':
    - oas2-oneOf
    - oas2-valid-schema-example
    - operation-tag-defined
  'reference/catalog.v3.yml':
    - oas2-operation-security-defined
    - oas3-schema
    - oas2-schema
    - oas2-valid-media-example
    - oas2-valid-schema-example
  'reference/channels.v3.yml':
    - oas3-schema
    - oas3-valid-media-example
  'reference/current_customer.yml':
    - operation-success-response
  'reference/custom-template-associations.v3.yml':
    - openapi-tags
    - operation-tag-defined
  'reference/customer_login.yml':
    - operation-success-response
  'reference/email_templates.v3.yml':
    - oas3-schema
  'reference/geography.v2.yml':
    - oas2-valid-media-example
  'reference/orders.v2.oas2.yml':
    - oas3-valid-schema-example
    - oas3-valid-media-example
    - oas3-schema
  'reference/orders.v3.yml':
    - oas2-valid-schema-example
    - oas2-valid-media-example
    - oas2-anyOf
  'reference/settings.v3.yml':
    - oas3-valid-media-example
  'reference/sites.v3.yml':
    - oas2-valid-media-example
  'reference/store_information.v2.yml':
    - oas2-valid-media-example
    - oas2-valid-schema-example
  'reference/themes.v3.yml':
    - oas3-schema
  'reference/webhooks.v3.yml':
    - oas3-valid-media-example
  'carts.v3.yml':
    - oas2-oneOf
    - oas2-valid-schema-example
  'catalog.v3.yml':
    - oas2-operation-security-defined
    - oas3-schema
    - oas2-schema
    - oas2-valid-media-example
    - oas2-valid-schema-example
  'channels.v3.yml':
    - oas3-schema
    - oas3-valid-media-example
  'current_customer.yml':
    - operation-success-response
  'customer_login.yml':
    - operation-success-response
  'email_templates.v3.yml':
    - oas3-schema
  'geography.v2.yml':
    - oas2-valid-media-example
  'orders.v2.oas2.yml':
    - oas3-valid-schema-example
    - oas3-valid-media-example
    - oas3-schema
  'orders.v3.yml':
    - oas2-valid-schema-example
    - oas2-valid-media-example
    - oas2-anyOf
  'settings.v3.yml':
    - oas3-valid-media-example
  'sites.v3.yml':
    - oas2-valid-media-example
  'store_information.v2.yml':
    - oas2-valid-media-example
    - oas2-valid-schema-example
  'themes.v3.yml':
    - oas3-schema
  'webhooks.v3.yml':
    - oas3-valid-media-example
  'pages.v3.yml':
    - oas3-valid-media-example
    - oas3-valid-schema-example
