openapi: 3.0.0
info:
  title: Store Metafields REST API
  version: 1.0.0
paths:
  /stores/{store_hash}/v3/store/metafields:
    post:
      summary: Batch create metafields
      operationId: batchCreateMetafields
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string
                  namespace:
                    type: string
                  permission_set:
                    type: string
                  description:
                    type: string
      responses:
        '200':
          description: Metafields created successfully
      security:
        - authToken: []
    put:
      summary: Batch update metafields
      operationId: batchUpdateMetafields
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  namespace:
                    type: string
      responses:
        '200':
          description: Metafields updated successfully
      security:
        - authToken: []
    delete:
      summary: Batch delete metafields
      operationId: batchDeleteMetafields
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
      responses:
        '200':
          description: Metafields deleted successfully
      security:
        - authToken: []
  
  /stores/{store_hash}/v3/store/metafields/{metafield_id}:
    put:
      summary: Update metafield
      operationId: updateMetafield
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
        - name: metafield_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                namespace:
                  type: string
      responses:
        '200':
          description: Metafield updated successfully
      security:
        - authToken: []
    delete:
      summary: Delete metafield
      operationId: deleteMetafield
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
        - name: metafield_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Metafield deleted successfully
      security:
        - authToken: []

  /stores/{store_hash}/v3/customers/{customer_id}/metafields/{metafield_id}:
    get:
      summary: Get metafield for customer
      operationId: getCustomerMetafield
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
        - name: customer_id
          in: path
          required: true
          schema:
            type: integer
        - name: metafield_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Metafield retrieved successfully
      security:
        - authToken: []

  /stores/{store_hash}/v3/catalog/products/metafields:
    get:
      summary: List metafields for products
      operationId: listProductMetafields
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Metafields listed successfully
      security:
        - authToken: []

components:
  securitySchemes:
    authToken:
      type: apiKey
      in: header
      name: X-Auth-Token
