name: Rebuild Production Dev Center

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check for running builds and cancel
      run: |
        # Fetch running pipelines
        RUNNING_PIPELINES=$(curl --location --request GET "https://circleci.com/api/v2/project/gh/bigcommerce/developer-center/pipeline?branch=main" \
          --header "Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}" \
          | jq -r '.items[] | select(.state == "running") | .id')

        echo $RUNNING_PIPELINES
        
        # Cancel each running pipeline
        for PIPELINE_ID in $RUNNING_PIPELINES; do
          curl --location --request POST "https://circleci.com/api/v2/pipeline/$PIPELINE_ID/cancel" \
            --header "Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}"
        done

    - name: Trigger CircleCI Build
      run: |
        curl --location 'https://circleci.com/api/v2/project/gh/bigcommerce/developer-center/pipeline' \
        --header 'Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
            "branch": "main",
             "parameters": {
                 "build_environment": "production",
                 "github_triggering_actor": "${{ github.actor }}"
             }
        }'
      env:
        CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
