name: List Repository Contents

on: [push]

jobs:
  list-contents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List contents of the repository
        run: |
          echo "Listing all contents of the repository:"
          ls -R
